version: '3'
services:
    node:
        build: .
        command: 'yarn workspace proton-mail start'
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        expose:
            - '8080'
        ports:
            - '8080:8080'
